export enum FailureCode {
  ValidationError = "VALIDATION_ERROR",
  IdempotencyKeyMissing = "IDEMPOTENCY_KEY_MISSING",
  IdempotencyConflict = "IDEMPOTENCY_CONFLICT",
  InvalidCursor = "INVALID_CURSOR",
  WalletAlreadyExists = "WALLET_ALREADY_EXISTS",
  WalletNotFound = "WALLET_NOT_FOUND",
  TransactionNotFound = "TRANSACTION_NOT_FOUND",
  CurrencyMismatch = "CURRENCY_MISMATCH",
  InsufficientBalance = "INSUFFICIENT_BALANCE",
  ReferenceNotFound = "REFERENCE_NOT_FOUND",
  ReferenceMismatch = "REFERENCE_MISMATCH",
  ReversalWouldOverdraw = "REVERSAL_WOULD_OVERDRAW",
  ReferenceAlreadyUsed = "REFERENCE_ALREADY_USED",
  ReferenceWrongKind = "REFERENCE_WRONG_KIND",
  ReferenceTimeout = "REFERENCE_TIMEOUT",
  TransientInfrastructureFailure = "TRANSIENT_INFRASTRUCTURE_FAILURE",
  UnexpectedError = "UNEXPECTED_ERROR",
  InternalError = "INTERNAL_ERROR",
}
